# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Dask Data Chunking
author: Author
copyright: "2023"
# logo: logo.png

exclude_patterns : [_build, Thumbs.db, .nox, .DS_Store, "*.ipynb_checkpoints", "*.zarr", .pytest_cache  ]
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: false

repository:
  url: https://github.com/gzt5142/DaskDataChunking 
  branch: main  

html:
  use_issues_button: true
  use_repository_button: true
  use_search_button: false
  announcement: "This is a work in progress..."

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

sphinx:   
  recursive_update: true
  # extra_extensions:  ['sphinxcontrib.bibtex']
  config:
    # bibtex_reference_style: author_year
    # bibtex_bibfiles: ['references.bib']
    html_extra_path: ['env.yml', 'requirements.txt']
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js