# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Dask Data Chunking
author: HyTEST Team
copyright: "2023"
logo: assets/HyTEST_Badge.svg

exclude_patterns : [_build, Thumbs.db, .nox, .DS_Store, "*.ipynb_checkpoints", "*.zarr", .pytest_cache  ]
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: true

repository:
  url: https://github.com/gzt5142/DaskDataChunking 
  branch: main  

html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  announcement: "Work in progress..."

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution
    - tasklist

sphinx:   
  recursive_update: true
  # Disabling bibtex unless we need it. 
  # extra_extensions:  ['sphinxcontrib.bibtex'] 
  config:
          # html_extra_path: ["performance_reports"]
    # bibtex_reference_style: author_year
    # bibtex_bibfiles: ['references.bib']
    # ignore/suppress warnings for "unknown: mime types: application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
    suppress_warnings: ["mystnb.unknown_mime_type"]
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
